#!/usr/bin/env python
import rospy
from sensor_msgs.msg import JointState

from markers import *
from lab3functions import *

rospy.init_node("jointsNode")
pub = rospy.Publisher('joint_states', JointState, queue_size=1)
bmarker = BallMarker(color['GREEN'])

# Joint names
jnames = ("joint1", "joint2", "joint3",
          "joint4_new", "joint4", "joint5", "joint6")
# Joint Configuration
q = [0, 0, 0, 0, 0, 0, 0]
# q = [pi, pi/3, 0.6, 0.2, pi/4, 0.2, 3.14]

# End effector with respect to the base
T = fkine_irb(q)
print(np.round(T, 3))
bmarker.position(T)

# Object (message) whose type is JointState
jstate = JointState()
# Set values to the message
jstate.header.stamp = rospy.Time.now()
jstate.name = jnames
# Add the head joint value (with value 0) to the joints
jstate.position = q

# Loop rate (in Hz)
rate = rospy.Rate(20)
# Continuous execution loop
while not rospy.is_shutdown():
    # Current time (needed for ROS)
    jstate.header.stamp = rospy.Time.now()
    # Publish the message
    pub.publish(jstate)
    bmarker.publish()
    # Wait for the next iteration
    rate.sleep()
